hhld.pwr.cons <- read.table("household_power_consumption.txt", header = TRUE, sep=";", na.strings = "?")
hhld.pwr.cons$AsDate <- as.Date(hhld.pwr.cons$Date, format="%d/%m/%Y")
hhld.pwr.cons.filtered <- subset(hhld.pwr.cons, AsDate >= as.Date("2007-02-01") & AsDate <= as.Date("2007-02-02"))
hhld.pwr.cons.filtered$DateTime <- strptime(paste(hhld.pwr.cons.filtered$Date, hhld.pwr.cons.filtered$Time), format="%d/%m/%Y %H:%M:%S")
png("plot2.png",width=480,height=480)
plot(hhld.pwr.cons.filtered$DateTime, hhld.pwr.cons.filtered$Global_active_power, type="l", xlab="", ylab="Global Active Power (kilowatts)")
dev.off()
rm(hhld.pwr.cons.filtered)
rm(hhld.pwr.cons)
