hhld.pwr.cons <- read.table("household_power_consumption.txt", header = TRUE, sep=";", na.strings = "?")
hhld.pwr.cons$AsDate <- as.Date(hhld.pwr.cons$Date, format="%d/%m/%Y")
hhld.pwr.cons.filtered <- subset(hhld.pwr.cons, AsDate >= as.Date("2007-02-01") & AsDate <= as.Date("2007-02-02"))
hhld.pwr.cons.filtered$DateTime <- strptime(paste(hhld.pwr.cons.filtered$Date, hhld.pwr.cons.filtered$Time), format="%d/%m/%Y %H:%M:%S")
png("plot4.png",width=480,height=480)
par(mfrow = c(2, 2), cex=0.65)
plot(hhld.pwr.cons.filtered$DateTime, hhld.pwr.cons.filtered$Global_active_power, type="l", xlab="", ylab="Global Active Power")
plot(hhld.pwr.cons.filtered$DateTime, hhld.pwr.cons.filtered$Voltage, type="l", xlab="datetime", ylab="Voltage")
plot(hhld.pwr.cons.filtered$DateTime, hhld.pwr.cons.filtered$Sub_metering_1, type="l", xlab="", ylab="Energy sub metering")
lines(hhld.pwr.cons.filtered$DateTime, hhld.pwr.cons.filtered$Sub_metering_2, col="red")
lines(hhld.pwr.cons.filtered$DateTime, hhld.pwr.cons.filtered$Sub_metering_3, col="blue")
legend("topright", col=c("black", "red", "blue"), cex = 0.95, lty=1, border=NULL, legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
plot(hhld.pwr.cons.filtered$DateTime, hhld.pwr.cons.filtered$Global_reactive_power, type="l", xlab="datetime", ylab="Global_reactive_power")
dev.off()
rm(hhld.pwr.cons.filtered)
rm(hhld.pwr.cons)
