hhld.pwr.cons <- read.table("household_power_consumption.txt", header = TRUE, sep=";", na.strings = "?")
hhld.pwr.cons$AsDate <- as.Date(hhld.pwr.cons$Date, format="%d/%m/%Y")
hhld.pwr.cons.filtered <- subset(hhld.pwr.cons, AsDate >= as.Date("2007-02-01") & AsDate <= as.Date("2007-02-02"))
png("plot1.png",width=480,height=480)
hist(hhld.pwr.cons.filtered$Global_active_power, col="red", main="Global Active Power", xlab="Global Active Power (kilowatts)", ylab="Frequency", axes=FALSE)
axis(1, at=seq(0 , 6, by=2), las=1)
axis(2, at=seq(0 , 1200, by=200))
dev.off()
rm(hhld.pwr.cons.filtered)
rm(hhld.pwr.cons)
